### ISSUE TITLE
undefined method conf_dir

### ISSUE THREAD

**Issue by rchekaluk** [RallySoftware-cookbooks/datomic#4]
Trying to use this cookbook via chef-solo. Am I missing some dependency?

```
================================================================================
Error executing action `enable` on resource 'java_service[datomic]'
================================================================================


NoMethodError
-------------
undefined method `conf_dir' for Chef::Resource::BluepillService


Cookbook Trace:
---------------
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java_service/providers/default.rb:108:in `block in delegate_action'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java_service/providers/default.rb:106:in `delegate_action'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java_service/providers/default.rb:37:in `block in class_from_file'


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/datomic/providers/install.rb

 71:   java_service 'datomic' do
 72:     action [:create, :enable, :load, :start]
 73:     user username
 74:     working_dir run_dir
 75:     standard_options({:server => nil})
 76:     main_class 'clojure.main'
 77:     classpath Proc.new { Mixlib::ShellOut.new('bin/classpath', :cwd => run_dir).run_command.stdout.strip }
 78:     args(['--main', 'datomic.launcher', 'transactor.properties'])
 79:     pill_file_dir run_dir
 80:     log_file "#{run_dir}/datomic.log"
 81:     only_if { version_changing? }
 82:   end
 83: 



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/datomic/providers/install.rb:71:in `block in class_from_file'

java_service("datomic") do
  action [:create, :enable, :load, :start]
  updated true
  retries 0
  retry_delay 2
  cookbook_name :datomic
  user "datomic"
  working_dir "/home/datomic/datomic"
  standard_options {:server=>nil}
  main_class "clojure.main"
  classpath #<Proc:0x000000036f8918@/tmp/vagrant-chef-1/chef-solo-1/cookbooks/datomic/providers/install.rb:77>
  args ["--main", "datomic.launcher", "transactor.properties"]
  pill_file_dir "/home/datomic/datomic"
  log_file "/home/datomic/datomic/datomic.log"
  service_name "datomic"
  only_if { #code block }
end




================================================================================
Error executing action `install` on resource 'datomic_install[datomic]'
================================================================================


NoMethodError
-------------
java_service[datomic] (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/datomic/providers/install.rb line 71) had an error: NoMethodError: undefined method `conf_dir' for Chef::Resource::BluepillService


Cookbook Trace:
---------------
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java_service/providers/default.rb:108:in `block in delegate_action'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java_service/providers/default.rb:106:in `delegate_action'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java_service/providers/default.rb:37:in `block in class_from_file'


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/datomic/recipes/default.rb

 30: datomic_install node[:datomic][:user]



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/datomic/recipes/default.rb:30:in `from_file'

datomic_install("datomic") do
  action :install
  updated true
  updated_by_last_action true
  retries 0
  retry_delay 2
  cookbook_name :datomic
  recipe_name "default"
end



An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'default'
machine. Please handle this error then try again:

Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by ghost** [comment]
This is no longer used at Rally / CA
